### ISSUE TITLE
🚀 Saisir les données

### ISSUE THREAD

**Issue by adriens** [opt-nc/odata-acronyms#1]
- [x] Récupérer le pdf
- [x] Extraire les données
- [x] Les charger dans un csv
- [x] Upload en Kaggle dataset
- [x] Pousser un Notebook
- [x] #3

**Comment by adriens** [comment]
https://office.opt.nc/sites/corporate/files/media/file/repertoire_des_emplois_opt-nc_2017.pdf

**Comment by adriens** [comment]
- [repertoire_des_emplois_opt-nc_2017.pdf](https://github.com/opt-nc/odata-acronyms/files/14503135/repertoire_des_emplois_opt-nc_2017.pdf)

**Comment by adriens** [comment]
Kaggle en cours de préparation...

**Comment by adriens** [comment]
🥳  [📘 Lexique des acronymes de l’OPT-NC](https://www.kaggle.com/datasets/optnouvellecaldonie/lexique-des-acronymes-de-lopt-nc/)

**Comment by adriens** [comment]
- https://github.com/opt-nc/odata-acronyms/issues/3

**Comment by adriens** [comment]
Noetbook in progress...

**Comment by adriens** [comment]
https://www.kaggle.com/code/optnouvellecaldonie/acronymes-opt-nc-for-dummies

**Comment by adriens** [comment]
:partying_face: **Score d'utilisabilité : 10**
![image](https://github.com/opt-nc/odata-acronyms/assets/5235127/ea02aa0d-6322-49f6-a26c-d9bb71348c9f)

**Comment by adriens** [comment]
En attente de : 

- #3

**Comment by mbarre** [comment]
@adriens , c'est fait .
Il y juste un souci avec le check de l'ordre des acronyms qd ce sont les mêmes valeurs.
cf : #5

**Comment by adriens** [comment]
Ptet feinter avec un distinct ?

**Comment by mbarre** [comment]
J'ai ajouté la description pour définir l'ordre.
