### ISSUE TITLE
Ajouter acronyme CTD

### ISSUE THREAD

**Issue by adriens** [opt-nc/odata-acronyms#11]
# 🎯 Actions

- [x] Prendre connaissance de [📘 Lexique des acronymes de l’OPT-NC](https://www.kaggle.com/datasets/optnouvellecaldonie/lexique-des-acronymes-de-lopt-nc)
- [x] Prendre connaissance de [👨‍🎓 Acronymes OPT-NC for dummies](https://www.kaggle.com/code/optnouvellecaldonie/acronymes-opt-nc-for-dummies)
- [x] Lire et comprendre [🪄 DuckDB sql hack : get things SORTED w/ constraint CHECK](https://dev.to/adriens/duckdb-sql-hack-get-things-sorted-w-constraint-check-46c)
- [x] Lire et comprendre [🦆 Effortless Data Quality w/duckdb on GitHub ♾️](https://dev.to/optnc/effortless-data-quality-wduckdb-on-github-2mkb)
- [x] Ajouter l'acronyme `CTD`

**Comment by Supervinh** [comment]
Petit problème de typo dans [📘 Lexique des acronymes de l’OPT-NC](https://www.kaggle.com/datasets/optnouvellecaldonie/lexique-des-acronymes-de-lopt-nc)

![Image](https://github.com/user-attachments/assets/5dc84f81-80a5-49ea-b144-897fb10dcda8)

**Comment by Supervinh** [comment]
Est-ce que cela veut dire que Section Intervention = Système d’Information ? Ou simplement que le même ID est utilisé pour les 2 ?

![Image](https://github.com/user-attachments/assets/8bd2ca1e-0dd1-4817-986c-44cb311bb2b4)

**Comment by adriens** [comment]
> Petit problème de typo dans [📘 Lexique des acronymes de l’OPT-NC](https://www.kaggle.com/datasets/optnouvellecaldonie/lexique-des-acronymes-de-lopt-nc)

Sur les étoiles pour mettre en gras ?

**Comment by adriens** [comment]
> Est-ce que cela veut dire que Section Intervention = Système d’Information ? Ou simplement que le même ID est utilisé pour les 2 ?
> Ou simplement que le même ID est utilisé pour les 2 ?

cf le pdf : 

![Image](https://github.com/user-attachments/assets/57c72cc9-046a-4dde-9be6-98968bec7a24)

**Comment by adriens** [comment]
Typo fixée : ![Image](https://github.com/user-attachments/assets/1ddfaf6b-74f9-4ac7-bfa5-f11e11ce5256)

**Comment by Supervinh** [comment]
> > Est-ce que cela veut dire que Section Intervention = Système d’Information ? Ou simplement que le même ID est utilisé pour les 2 ?
> > Ou simplement que le même ID est utilisé pour les 2 ?
> 
> cf le pdf :

Mais pourquoi ne pas avoir distingué comme CAO par exemple ?

![Image](https://github.com/user-attachments/assets/9845c30b-cb08-496d-8f49-198a87806456)

**Comment by Supervinh** [comment]
Proposition pour l'acronyme CTD 

![Image](https://github.com/user-attachments/assets/00aca33b-82d4-445b-a6ae-5e88ce7194df)

**Comment by adriens** [comment]
Oula, non, trop risqué, openAI peut halluciner. Demander à des ressources internes svp.

**Comment by Supervinh** [comment]
@adriens Vu avec Ronan, CTD = Commission Technique de Dépouillement

**Comment by adriens** [comment]
je refresh le dataset 👍

**Comment by adriens** [comment]
👌 
![Image](https://github.com/user-attachments/assets/91009774-1c22-4bd2-9808-a8481f3f6981)

**Comment by adriens** [comment]
[🕵️ OSINT: link company acronyms to Standard Occupation Classification w. Open Source LLMs](https://dev.to/adriens/osint-link-company-acronyms-to-standard-occupation-classification-w-open-source-llms-5c6o)
